api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        html:     ['text/html']
        json:     ['application/json']
        jsonapi:  ['application/vnd.api+json']
    graphql:
            graphiql:
                enabled: true
    collection:
            pagination:
                client_items_per_page: true
                items_per_page_parameter_name: 'pageSize'
