#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User


easy_admin:
  entities:
    Content:
      class: Bolt\Entity\Content
      list:
        fields: ['id', 'contenttype', 'fields', 'author_id', 'status', 'created_at']
    Field:
      class: Bolt\Entity\Field
    User:
      class: Bolt\Entity\User
